# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  OpenCV_config = debug
  Miniz_config = debug
  Cam_Core_config = debug
  CamClient_config = debug
  CamServer_config = debug
  CamDisplay_config = debug
  UpdateClient_config = debug
  UpdateServer_config = debug
endif
ifeq ($(config),release)
  OpenCV_config = release
  Miniz_config = release
  Cam_Core_config = release
  CamClient_config = release
  CamServer_config = release
  CamDisplay_config = release
  UpdateClient_config = release
  UpdateServer_config = release
endif

PROJECTS := OpenCV Miniz Cam-Core CamClient CamServer CamDisplay UpdateClient UpdateServer

.PHONY: all clean help $(PROJECTS) Cam Core Dependencies Updater

all: $(PROJECTS)

Cam: CamClient CamDisplay CamServer

Core: Cam-Core

Dependencies: Miniz OpenCV

Updater: UpdateClient UpdateServer

OpenCV:
ifneq (,$(OpenCV_config))
	@echo "==== Building OpenCV ($(OpenCV_config)) ===="
	@${MAKE} --no-print-directory -C CamClient/vendor/opencv -f Makefile config=$(OpenCV_config)
endif

Miniz:
ifneq (,$(Miniz_config))
	@echo "==== Building Miniz ($(Miniz_config)) ===="
	@${MAKE} --no-print-directory -C vendor/miniz -f Makefile config=$(Miniz_config)
endif

Cam-Core:
ifneq (,$(Cam_Core_config))
	@echo "==== Building Cam-Core ($(Cam_Core_config)) ===="
	@${MAKE} --no-print-directory -C Cam-Core -f Makefile config=$(Cam_Core_config)
endif

CamClient: Cam-Core
ifneq (,$(CamClient_config))
	@echo "==== Building CamClient ($(CamClient_config)) ===="
	@${MAKE} --no-print-directory -C CamClient -f Makefile config=$(CamClient_config)
endif

CamServer: Cam-Core
ifneq (,$(CamServer_config))
	@echo "==== Building CamServer ($(CamServer_config)) ===="
	@${MAKE} --no-print-directory -C CamServer -f Makefile config=$(CamServer_config)
endif

CamDisplay: Cam-Core
ifneq (,$(CamDisplay_config))
	@echo "==== Building CamDisplay ($(CamDisplay_config)) ===="
	@${MAKE} --no-print-directory -C CamDisplay -f Makefile config=$(CamDisplay_config)
endif

UpdateClient: Cam-Core Miniz
ifneq (,$(UpdateClient_config))
	@echo "==== Building UpdateClient ($(UpdateClient_config)) ===="
	@${MAKE} --no-print-directory -C UpdateClient -f Makefile config=$(UpdateClient_config)
endif

UpdateServer: Cam-Core Miniz
ifneq (,$(UpdateServer_config))
	@echo "==== Building UpdateServer ($(UpdateServer_config)) ===="
	@${MAKE} --no-print-directory -C UpdateServer -f Makefile config=$(UpdateServer_config)
endif

clean:
	@${MAKE} --no-print-directory -C CamClient/vendor/opencv -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/miniz -f Makefile clean
	@${MAKE} --no-print-directory -C Cam-Core -f Makefile clean
	@${MAKE} --no-print-directory -C CamClient -f Makefile clean
	@${MAKE} --no-print-directory -C CamServer -f Makefile clean
	@${MAKE} --no-print-directory -C CamDisplay -f Makefile clean
	@${MAKE} --no-print-directory -C UpdateClient -f Makefile clean
	@${MAKE} --no-print-directory -C UpdateServer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   OpenCV"
	@echo "   Miniz"
	@echo "   Cam-Core"
	@echo "   CamClient"
	@echo "   CamServer"
	@echo "   CamDisplay"
	@echo "   UpdateClient"
	@echo "   UpdateServer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"